import Head from "next/head";
import {useDispatch, useSelector} from "react-redux";
import styles from "../styles/Home.module.css";
import {useRouter} from "next/router";
import {logout} from "../api/auth";

import {IAuthState} from "../redux/store";

export default function Home() {
  const dispatch = useDispatch();
  const currentUser = useSelector(
    (state: IAuthState) => state.auth.currentUser
  );
  const router = useRouter();
  if (!currentUser) {
    router.push("/login");
  } else {
    return (
      <div className={styles.container}>
        <Head>
          <title>Home</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h2>Hello {currentUser?.email}</h2>
        <button onClick={() => logout(dispatch)}>Log out</button>
      </div>
    );
  }
}
